version: "3.7"

services:
  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - ./docker/postgres/postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
