// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Node interface {
	IsNode()
}

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Project) IsNode() {}
